# Generated by Django 5.2.4 on 2025-07-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Imperatriz'), ('GALAXIA', 'Rainha'), ('ESTRELA', 'Princesa'), ('PLANETA', 'Condessa')], default='', max_length=50),
        ),
    ]
